### ISSUE TITLE
Learning JNI

### ISSUE THREAD

**Issue by Noitidart** [cscott/intent-addon#2]
This block of code right here is crashing android today:

https://github.com/cscott/intent-addon/blob/master/lib/main.js#L74-L78

```
    // hacky way to get activity context
    JNI.LoadClass(jenv, "org.mozilla.gecko.GeckoApp", {
        static_fields: [
            { name: "mAppContext", sig: "Lorg/mozilla/gecko/GeckoApp;" }
        ],
    });
```

What would be the alternative? Coo lstuff

**Comment by cscott** [comment]
Perhaps Firefox on Android has a better way to get the activity context
now?  I believe I filed a bug at the time I wrote this code requesting an
official interface for this.

**Comment by Noitidart** [comment]
Thanks so much for your incredible work, the official interface landed, your JSM module is exposed to the `window.JNI` object by default and there is a `window.jenv` default object. Here is the JSM:

https://dxr.mozilla.org/mozilla-central/source/mobile/android/modules/JNI.jsm

Thanks for this absolutely incredible work Dr! I am a JS guy who learned C (WinAPI, Carbon, CoreFoun, , ObjC, GDK, GTK, X11), and COM by using it from js-ctypes over the last year.

I found this way to get the context and it didnt crash:

https://github.com/mozilla/firefox-for-android-addons/blob/355f9a01464a0794c1084e8fdbab92c58503f49a/snippets/jni.js#L23-L44

I'm trying to learn by writing a simple conversion of this toast code:

http://developer.android.com/reference/android/widget/Toast.html

```
Context context = getApplicationContext();
CharSequence text = "Hello toast!";
int duration = Toast.LENGTH_SHORT;

Toast toast = Toast.makeText(context, text, duration);
toast.show();
```

My progress is pretty bad haha would you be able to write the JNI version for me, I learned objc and all the stuff in the past the fastest when I had side by side Target(ie:JNI) to Native examples.

I'll take what I learn from you and update the ctypes documentation (I do a ton of this) ie: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/Standard_OS_Libraries

I was thinking of adding a JNI section with an android specific section to this page, and of course updating examples section as well like where I have the COM and objc stuff:
- https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes#Examples

**Comment by Noitidart** [comment]
Got it! That was such a beutiful experience! Thank you so much for this awesome bridge!!

https://gist.github.com/Noitidart/400261f83b1be721a93a#comment-1492825
